/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            colors: {
                forest: {
                    50: '#f4f7f4',
                    100: '#e3ebe3',
                    200: '#c7d7c7',
                    300: '#a1bba1',
                    400: '#759b75',
                    500: '#557e55',
                    600: '#2D4A3E',
                    700: '#1F362E',
                    800: '#152A23',
                    900: '#0E1D18',
                },
                earth: {
                    50: '#FAF5EF',
                    100: '#F0E6D3',
                    200: '#E0CCAA',
                    300: '#D0B27E',
                    400: '#C49D5C',
                    500: '#8B6F47',
                    600: '#7D572E',
                    700: '#684A2B',
                    800: '#573F28',
                    900: '#3D2C1C',
                },
                cream: {
                    50: '#FDFBF7',
                    100: '#F5F0E8',
                    200: '#EDE5D8',
                    300: '#E0D4C0',
                },
                gold: {
                    400: '#D4A84B',
                    500: '#C9A84C',
                    600: '#B8943A',
                },
                charcoal: '#1A1A1A',
            },
            fontFamily: {
                sans: ['DM Sans', 'system-ui', '-apple-system', 'sans-serif'],
                display: ['Sora', 'system-ui', 'sans-serif'],
                mono: ['DM Mono', 'JetBrains Mono', 'monospace'],
            },
            backgroundImage: {
                'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E\")",
                'noise-light': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.03'/%3E%3C/svg%3E\")",
            },
            boxShadow: {
                'warm': '0 4px 24px rgba(45, 74, 62, 0.08), 0 2px 8px rgba(45, 74, 62, 0.04)',
                'warm-lg': '0 8px 40px rgba(45, 74, 62, 0.12), 0 4px 16px rgba(45, 74, 62, 0.06)',
                'warm-xl': '0 16px 64px rgba(45, 74, 62, 0.16), 0 8px 24px rgba(45, 74, 62, 0.08)',
                'inner-warm': 'inset 0 2px 4px rgba(45, 74, 62, 0.04)',
                'glass': '0 4px 30px rgba(0, 0, 0, 0.08)',
            },
            animation: {
                'fade-in': 'fadeIn 0.6s ease-out forwards',
                'fade-up': 'fadeUp 0.6s ease-out forwards',
                'fade-down': 'fadeDown 0.6s ease-out forwards',
                'scale-in': 'scaleIn 0.4s ease-out forwards',
                'slide-left': 'slideLeft 0.6s ease-out forwards',
                'slide-right': 'slideRight 0.6s ease-out forwards',
                'float': 'float 6s ease-in-out infinite',
                'pulse-soft': 'pulseSoft 3s ease-in-out infinite',
            },
            keyframes: {
                fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
                fadeUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
                fadeDown: { '0%': { opacity: '0', transform: 'translateY(-16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
                scaleIn: { '0%': { opacity: '0', transform: 'scale(0.9)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
                slideLeft: { '0%': { opacity: '0', transform: 'translateX(-24px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
                slideRight: { '0%': { opacity: '0', transform: 'translateX(24px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
                float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
                pulseSoft: { '0%, 100%': { opacity: '0.4' }, '50%': { opacity: '0.8' } },
            },
        },
    },
    plugins: [],
};
